// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxLCjLdxtz2bmKLht2-7UCGpF2jjSpjsA',
    appId: '1:909441169980:web:1ccea0b46bf0edbbb8e139',
    messagingSenderId: '909441169980',
    projectId: 'final-project-885e6',
    authDomain: 'final-project-885e6.firebaseapp.com',
    storageBucket: 'final-project-885e6.appspot.com',
    measurementId: 'G-M7HETWE84M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbhFkXSnvSYWyRWO7sXkw-KonsCkOTGMg',
    appId: '1:909441169980:android:7b98e6190f74c55cb8e139',
    messagingSenderId: '909441169980',
    projectId: 'final-project-885e6',
    storageBucket: 'final-project-885e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoxOfKicrhtags2qON74LSaC7TBC9WeNU',
    appId: '1:909441169980:ios:ad383170b9c02005b8e139',
    messagingSenderId: '909441169980',
    projectId: 'final-project-885e6',
    storageBucket: 'final-project-885e6.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoxOfKicrhtags2qON74LSaC7TBC9WeNU',
    appId: '1:909441169980:ios:57e1cd584562369fb8e139',
    messagingSenderId: '909441169980',
    projectId: 'final-project-885e6',
    storageBucket: 'final-project-885e6.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
